version: '3.5'

services:
  db: 
    container_name: postgres-db
    image: postgres:15-alpine3.18
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 9411:9411
        - 4317:4317
        - 4318:4318

  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.9.14-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
